services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: restyle
      POSTGRES_PASSWORD: restyle
      POSTGRES_DB: restyle
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
