import manifest from "@/data/examples.json";

// Before/after images generated by scripts/generate-examples.ts into public/examples.
// The manifest lists which room × style pairs have one; pages without an example simply
// skip the section, so examples can be rolled out in batches. Every batch is reviewed by eye;
// an entry with `rejected` stays in the manifest (so it is not regenerated) but is never shown.

const available = manifest as Record<string, { promptVersion: string; generatedAt: string; rejected?: string }>;

export type Example = { before: string; after: string };

export function exampleFor(room: string, style: string): Example | null {
  const entry = available[`${room}--${style}`];
  if (!entry || entry.rejected) return null;
  return { before: `/examples/${room}--before.webp`, after: `/examples/${room}--${style}.webp` };
}
